version: '3'

services:
  server:
    container_name: cats-server
    build: docker/server
    ports:
      - 8090:8090
      - 5858:5858
    volumes:
      - ./:/var/www/cats
    environment:
      - COMPOSE_HTTP_TIMEOUT=300
    tty: true
    networks:
      - cats_network

  database:
    container_name: database
    build: docker/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example
    networks:
      - cats_network

networks:
  cats_network:
    external: true
