version: '3'

services:
  server:
    container_name: cats-server
    build: docker/server
    ports:
      - 8090:8090
      - 5858:5858
    volumes:
      - ./:/var/www/cats
    environment:
      - COMPOSE_HTTP_TIMEOUT=300
    tty: true
    networks:
      - cats_network

  mongodb:
    container_name: cats-mongodb
    build: docker/db
    ports:
      - 27017:27017
    volumes:
      - ./.data/mongodb:/data/db
    networks:
      - cats_network


networks:
  cats_network:
    external: true
